"""T4.11: offline tests for review.md line-number accuracy and the
section-grouped .puml emission (T4.7/T4.8). Line numbers are asserted
against the actual emitted .puml text, not hardcoded -- if
generate/puml.py's layout ever shifts, this test shifts with it rather
than silently passing against a stale expectation.
"""

from __future__ import annotations

from umlregen.generate.puml import ir_to_puml
from umlregen.generate.review import build_review
from umlregen.ir.models import Class, Diagram, RelKind, Relationship


def _diagram(*, rel_confidences: list[float]) -> Diagram:
    classes = [
        Class(id="A", name="A", kind="class"),
        Class(id="B", name="B", kind="class"),
        Class(id="C", name="C", kind="class"),
    ]
    kinds = [RelKind.ASSOCIATION, RelKind.DEPENDENCY, RelKind.INHERITANCE]
    relationships = [
        Relationship(source="A", target="B", kind=kinds[0], confidence=rel_confidences[0], evidence="evidence 0"),
        Relationship(source="B", target="C", kind=kinds[1], confidence=rel_confidences[1], evidence="evidence 1"),
        Relationship(source="C", target="A", kind=kinds[2], confidence=rel_confidences[2], evidence="evidence 2"),
    ]
    return Diagram(classes=classes, relationships=relationships)


def test_flagged_relationship_line_numbers_match_the_actual_puml() -> None:
    diagram = _diagram(rel_confidences=[0.5, 0.1, 0.5])  # only the middle one is below a 0.3 threshold
    puml_text = ir_to_puml(diagram)
    review_text = build_review(diagram, threshold=0.3)

    puml_lines = puml_text.splitlines()

    import re

    cited_lines = [int(m.group(1)) for m in re.finditer(r"`\.puml:(\d+)`", review_text)]
    assert len(cited_lines) == 1

    cited_line_content = puml_lines[cited_lines[0] - 1]  # 1-indexed
    # The flagged relationship is B -> C, dependency (evidence "evidence 1").
    assert "B" in cited_line_content
    assert "C" in cited_line_content
    assert "..>" in cited_line_content  # dependency arrow, per generate/puml.py's _REL_ARROWS


def test_no_flagged_relationships_produces_a_valid_non_error_file() -> None:
    diagram = _diagram(rel_confidences=[0.5, 0.5, 0.5])
    review_text = build_review(diagram, threshold=0.3)
    assert "No relationships fall below the confidence threshold." in review_text


def test_all_flagged_relationships_produces_correct_count() -> None:
    diagram = _diagram(rel_confidences=[0.1, 0.1, 0.1])
    review_text = build_review(diagram, threshold=0.3)
    assert "3 relationship(s) below threshold" in review_text
    assert review_text.count("evidence:") == 3


def test_evidence_string_appears_verbatim() -> None:
    diagram = _diagram(rel_confidences=[0.5, 0.0, 0.5])
    review_text = build_review(diagram, threshold=0.3)
    assert "evidence 1" in review_text


# ---------------------------------------------------------------------------
# T4.8: section-grouped emission and the optional header
# ---------------------------------------------------------------------------


def test_puml_has_classes_and_relationships_section_comments() -> None:
    diagram = _diagram(rel_confidences=[0.5, 0.5, 0.5])
    puml_text = ir_to_puml(diagram)
    lines = puml_text.splitlines()

    classes_idx = lines.index("' --- Classes ---")
    relationships_idx = lines.index("' --- Relationships ---")
    assert classes_idx < relationships_idx


def test_puml_omits_header_by_default() -> None:
    diagram = _diagram(rel_confidences=[0.5, 0.5, 0.5])
    puml_text = ir_to_puml(diagram)
    assert "Generated by" not in puml_text


def test_puml_header_names_the_model_when_requested() -> None:
    diagram = _diagram(rel_confidences=[0.5, 0.5, 0.5])
    puml_text = ir_to_puml(diagram, model_id="test/model-x")
    assert "test/model-x" in puml_text.splitlines()[1]


def test_puml_determinism_still_holds_with_header_and_theme() -> None:
    diagram = _diagram(rel_confidences=[0.5, 0.1, 0.5])
    first = ir_to_puml(diagram, model_id="test/model", include_theme=True)
    second = ir_to_puml(diagram, model_id="test/model", include_theme=True)
    assert first == second
